dist: trusty
language: ruby
before_install: sudo apt-get install lighttpd libfcgi-dev libmemcache-dev memcached
install:
  - gem env version | grep '^\(2\|1.\(8\|9\|[0-9][0-9]\)\)' || gem update --system
  - gem install rake -v '~> 0.9.6'
  - rake deps
script: rake ci
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-1.7
  - ree
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
